/**
 * Build script: reads web/dist/ and generates src/embedded-assets.ts
 * so that `bun build --compile` bundles the web UI into the binary.
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from "fs";
import { join, relative, extname } from "path";

const DIST_DIR = join(import.meta.dir, "..", "web", "dist");
const OUT_FILE = join(import.meta.dir, "..", "src", "embedded-assets.ts");

const MIME_TYPES: Record<string, string> = {
  ".html": "text/html; charset=utf-8",
  ".css": "text/css; charset=utf-8",
  ".js": "application/javascript; charset=utf-8",
  ".svg": "image/svg+xml",
  ".png": "image/png",
  ".ico": "image/x-icon",
  ".json": "application/json",
};

function walkDir(dir: string): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...walkDir(full));
    } else {
      files.push(full);
    }
  }
  return files;
}

const allFiles = walkDir(DIST_DIR);

const entries: string[] = [];
for (const absPath of allFiles) {
  const relPath = "/" + relative(DIST_DIR, absPath).replace(/\\/g, "/");
  const content = readFileSync(absPath);
  const base64 = content.toString("base64");
  const ext = extname(absPath);
  const mime = MIME_TYPES[ext] || "application/octet-stream";
  entries.push(`  "${relPath}": { mime: "${mime}", data: "${base64}" }`);
}

const code = `/**
 * Auto-generated embedded web assets.
 * Do not edit — regenerated by scripts/embed-assets.ts
 */

const ASSETS: Record<string, { mime: string; data: string }> = {
${entries.join(",\n")}
};

export function getEmbeddedAsset(path: string): { mime: string; body: Uint8Array } | null {
  const entry = ASSETS[path];
  if (!entry) return null;
  const binary = Uint8Array.from(atob(entry.data), (c) => c.charCodeAt(0));
  return { mime: entry.mime, body: binary };
}

export function hasEmbeddedAssets(): boolean {
  return Object.keys(ASSETS).length > 0;
}
`;

writeFileSync(OUT_FILE, code);
console.log(`[embed-assets] Embedded ${allFiles.length} files into src/embedded-assets.ts`);
